/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.1
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.11
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import type {
  Pet,
  FindPetsByStatusParams,
  FindPetsByTagsParams,
  UpdatePetWithFormParams,
  ApiResponse,
  UploadFileParams,
  GetInventory200,
  Order,
  User,
  LoginUserParams,
} from "./model";
import { rest } from "msw";
import { faker } from "@faker-js/faker";

/**
 * Update an existing pet by Id
 * @summary Update an existing pet
 */
export const updatePet = <TData = AxiosResponse<Pet>>(
  pet: Pet,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/pet`, pet, options);
};

/**
 * Add a new pet to the store
 * @summary Add a new pet to the store
 */
export const addPet = <TData = AxiosResponse<Pet>>(
  pet: Pet,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/pet`, pet, options);
};

/**
 * Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 */
export const findPetsByStatus = <TData = AxiosResponse<Pet[]>>(
  params?: FindPetsByStatusParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/pet/findByStatus`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 */
export const findPetsByTags = <TData = AxiosResponse<Pet[]>>(
  params?: FindPetsByTagsParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/pet/findByTags`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * Returns a single pet
 * @summary Find pet by ID
 */
export const getPetById = <TData = AxiosResponse<Pet>>(
  petId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/pet/${petId}`, options);
};

/**
 * @summary Updates a pet in the store with form data
 */
export const updatePetWithForm = <TData = AxiosResponse<unknown>>(
  petId: number,
  params?: UpdatePetWithFormParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/pet/${petId}`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * delete a pet
 * @summary Deletes a pet
 */
export const deletePet = <TData = AxiosResponse<unknown>>(
  petId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/pet/${petId}`, options);
};

/**
 * @summary uploads an image
 */
export const uploadFile = <TData = AxiosResponse<ApiResponse>>(
  petId: number,
  uploadFileBody: Blob,
  params?: UploadFileParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/pet/${petId}/uploadImage`, uploadFileBody, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 */
export const getInventory = <TData = AxiosResponse<GetInventory200>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/store/inventory`, options);
};

/**
 * Place a new order in the store
 * @summary Place an order for a pet
 */
export const placeOrder = <TData = AxiosResponse<Order>>(
  order: Order,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/store/order`, order, options);
};

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID
 */
export const getOrderById = <TData = AxiosResponse<Order>>(
  orderId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/store/order/${orderId}`, options);
};

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
 * @summary Delete purchase order by ID
 */
export const deleteOrder = <TData = AxiosResponse<unknown>>(
  orderId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/store/order/${orderId}`, options);
};

/**
 * This can only be done by the logged in user.
 * @summary Create user
 */
export const createUser = <TData = AxiosResponse<unknown>>(
  user: User,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/user`, user, options);
};

/**
 * Creates list of users with given input array
 * @summary Creates list of users with given input array
 */
export const createUsersWithListInput = <TData = AxiosResponse<User>>(
  user: User[],
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/user/createWithList`, user, options);
};

/**
 * @summary Logs user into the system
 */
export const loginUser = <TData = AxiosResponse<string>>(
  params?: LoginUserParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/user/login`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Logs out current logged in user session
 */
export const logoutUser = <TData = AxiosResponse<unknown>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/user/logout`, options);
};

/**
 * @summary Get user by user name
 */
export const getUserByName = <TData = AxiosResponse<User>>(
  username: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/user/${username}`, options);
};

/**
 * This can only be done by the logged in user.
 * @summary Update user
 */
export const updateUser = <TData = AxiosResponse<unknown>>(
  username: string,
  user: User,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/user/${username}`, user, options);
};

/**
 * This can only be done by the logged in user.
 * @summary Delete user
 */
export const deleteUser = <TData = AxiosResponse<unknown>>(
  username: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/user/${username}`, options);
};

export type UpdatePetResult = AxiosResponse<Pet>;
export type AddPetResult = AxiosResponse<Pet>;
export type FindPetsByStatusResult = AxiosResponse<Pet[]>;
export type FindPetsByTagsResult = AxiosResponse<Pet[]>;
export type GetPetByIdResult = AxiosResponse<Pet>;
export type UpdatePetWithFormResult = AxiosResponse<unknown>;
export type DeletePetResult = AxiosResponse<unknown>;
export type UploadFileResult = AxiosResponse<ApiResponse>;
export type GetInventoryResult = AxiosResponse<GetInventory200>;
export type PlaceOrderResult = AxiosResponse<Order>;
export type GetOrderByIdResult = AxiosResponse<Order>;
export type DeleteOrderResult = AxiosResponse<unknown>;
export type CreateUserResult = AxiosResponse<unknown>;
export type CreateUsersWithListInputResult = AxiosResponse<User>;
export type LoginUserResult = AxiosResponse<string>;
export type LogoutUserResult = AxiosResponse<unknown>;
export type GetUserByNameResult = AxiosResponse<User>;
export type UpdateUserResult = AxiosResponse<unknown>;
export type DeleteUserResult = AxiosResponse<unknown>;

export const getUpdatePetMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.random.word(),
  category: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.datatype.number({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([faker.random.word(), undefined]),
    },
    undefined,
  ]),
  photoUrls: Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => faker.random.word()),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.datatype.number({ min: 1, max: 10 }) },
      (_, i) => i + 1
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.datatype.number({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([faker.random.word(), undefined]),
    })),
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["available", "pending", "sold"]),
    undefined,
  ]),
});

export const getAddPetMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.random.word(),
  category: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.datatype.number({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([faker.random.word(), undefined]),
    },
    undefined,
  ]),
  photoUrls: Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => faker.random.word()),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.datatype.number({ min: 1, max: 10 }) },
      (_, i) => i + 1
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.datatype.number({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([faker.random.word(), undefined]),
    })),
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["available", "pending", "sold"]),
    undefined,
  ]),
});

export const getFindPetsByStatusMock = () =>
  Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.datatype.number({ min: undefined, max: undefined }),
      undefined,
    ]),
    name: faker.random.word(),
    category: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.datatype.number({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([faker.random.word(), undefined]),
      },
      undefined,
    ]),
    photoUrls: Array.from(
      { length: faker.datatype.number({ min: 1, max: 10 }) },
      (_, i) => i + 1
    ).map(() => faker.random.word()),
    tags: faker.helpers.arrayElement([
      Array.from(
        { length: faker.datatype.number({ min: 1, max: 10 }) },
        (_, i) => i + 1
      ).map(() => ({
        id: faker.helpers.arrayElement([
          faker.datatype.number({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([faker.random.word(), undefined]),
      })),
      undefined,
    ]),
    status: faker.helpers.arrayElement([
      faker.helpers.arrayElement(["available", "pending", "sold"]),
      undefined,
    ]),
  }));

export const getFindPetsByTagsMock = () =>
  Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => ({
    id: faker.helpers.arrayElement([
      faker.datatype.number({ min: undefined, max: undefined }),
      undefined,
    ]),
    name: faker.random.word(),
    category: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([
          faker.datatype.number({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([faker.random.word(), undefined]),
      },
      undefined,
    ]),
    photoUrls: Array.from(
      { length: faker.datatype.number({ min: 1, max: 10 }) },
      (_, i) => i + 1
    ).map(() => faker.random.word()),
    tags: faker.helpers.arrayElement([
      Array.from(
        { length: faker.datatype.number({ min: 1, max: 10 }) },
        (_, i) => i + 1
      ).map(() => ({
        id: faker.helpers.arrayElement([
          faker.datatype.number({ min: undefined, max: undefined }),
          undefined,
        ]),
        name: faker.helpers.arrayElement([faker.random.word(), undefined]),
      })),
      undefined,
    ]),
    status: faker.helpers.arrayElement([
      faker.helpers.arrayElement(["available", "pending", "sold"]),
      undefined,
    ]),
  }));

export const getGetPetByIdMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  name: faker.random.word(),
  category: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.datatype.number({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([faker.random.word(), undefined]),
    },
    undefined,
  ]),
  photoUrls: Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map(() => faker.random.word()),
  tags: faker.helpers.arrayElement([
    Array.from(
      { length: faker.datatype.number({ min: 1, max: 10 }) },
      (_, i) => i + 1
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.datatype.number({ min: undefined, max: undefined }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([faker.random.word(), undefined]),
    })),
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["available", "pending", "sold"]),
    undefined,
  ]),
});

export const getUploadFileMock = () => ({
  code: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  type: faker.helpers.arrayElement([faker.random.word(), undefined]),
  message: faker.helpers.arrayElement([faker.random.word(), undefined]),
});

export const getGetInventoryMock = () => ({
  clgyxudrc0000qk9k88w7cvkb: faker.datatype.number({
    min: undefined,
    max: undefined,
  }),
});

export const getPlaceOrderMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  petId: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  quantity: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  shipDate: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split(".")[0]}Z`,
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["placed", "approved", "delivered"]),
    undefined,
  ]),
  complete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
});

export const getGetOrderByIdMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  petId: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  quantity: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  shipDate: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split(".")[0]}Z`,
    undefined,
  ]),
  status: faker.helpers.arrayElement([
    faker.helpers.arrayElement(["placed", "approved", "delivered"]),
    undefined,
  ]),
  complete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
});

export const getCreateUsersWithListInputMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  username: faker.helpers.arrayElement([faker.random.word(), undefined]),
  firstName: faker.helpers.arrayElement([faker.random.word(), undefined]),
  lastName: faker.helpers.arrayElement([faker.random.word(), undefined]),
  email: faker.helpers.arrayElement([faker.random.word(), undefined]),
  password: faker.helpers.arrayElement([faker.random.word(), undefined]),
  phone: faker.helpers.arrayElement([faker.random.word(), undefined]),
  userStatus: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
});

export const getLoginUserMock = () => faker.random.word();

export const getGetUserByNameMock = () => ({
  id: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
  username: faker.helpers.arrayElement([faker.random.word(), undefined]),
  firstName: faker.helpers.arrayElement([faker.random.word(), undefined]),
  lastName: faker.helpers.arrayElement([faker.random.word(), undefined]),
  email: faker.helpers.arrayElement([faker.random.word(), undefined]),
  password: faker.helpers.arrayElement([faker.random.word(), undefined]),
  phone: faker.helpers.arrayElement([faker.random.word(), undefined]),
  userStatus: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    undefined,
  ]),
});

export const getSwaggerPetstoreOpenAPI31MSW = () => [
  rest.put("*/pet", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getUpdatePetMock())
    );
  }),
  rest.post("*/pet", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getAddPetMock())
    );
  }),
  rest.get("*/pet/findByStatus", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getFindPetsByStatusMock())
    );
  }),
  rest.get("*/pet/findByTags", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getFindPetsByTagsMock())
    );
  }),
  rest.get("*/pet/:petId", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getGetPetByIdMock())
    );
  }),
  rest.post("*/pet/:petId", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
  rest.delete("*/pet/:petId", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
  rest.post("*/pet/:petId/uploadImage", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getUploadFileMock())
    );
  }),
  rest.get("*/store/inventory", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getGetInventoryMock())
    );
  }),
  rest.post("*/store/order", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getPlaceOrderMock())
    );
  }),
  rest.get("*/store/order/:orderId", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getGetOrderByIdMock())
    );
  }),
  rest.delete("*/store/order/:orderId", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
  rest.post("*/user", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
  rest.post("*/user/createWithList", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getCreateUsersWithListInputMock())
    );
  }),
  rest.get("*/user/login", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getLoginUserMock())
    );
  }),
  rest.get("*/user/logout", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
  rest.get("*/user/:username", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getGetUserByNameMock())
    );
  }),
  rest.put("*/user/:username", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
  rest.delete("*/user/:username", (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, "Mocked status"));
  }),
];
