import "./globals.css";

if (process.env.NODE_ENV === "development" || process.env.NODE_ENV === "test") {
  if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
    if (typeof window === "undefined") {
      const { server } = await import("../lib/mock/server");
      server.listen({ onUnhandledRequest: "bypass" });
      console.log("start mock in server");
    }
  }
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
